# coding: utf-8

"""
    Vector Similarity Demo

    The test functionality and Query testing  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@hyper-space.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hyperspace
from hyperspace.models.collection_name_search_body import CollectionNameSearchBody  # noqa: E501
from hyperspace.rest import ApiException


class TestCollectionNameSearchBody(unittest.TestCase):
    """CollectionNameSearchBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionNameSearchBody(self):
        """Test CollectionNameSearchBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hyperspace.models.collection_name_search_body.CollectionNameSearchBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
