# coding: utf-8

"""
    Vector Similarity Demo

    The test functionality and Query testing  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@hyper-space.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hyperspace
from hyperspace.models.any_ofsearch_function_name_body import AnyOfsearchFunctionNameBody  # noqa: E501
from hyperspace.rest import ApiException


class TestAnyOfsearchFunctionNameBody(unittest.TestCase):
    """AnyOfsearchFunctionNameBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfsearchFunctionNameBody(self):
        """Test AnyOfsearchFunctionNameBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hyperspace.models.any_ofsearch_function_name_body.AnyOfsearchFunctionNameBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
