# coding: utf-8

# flake8: noqa

"""
    Vector Similarity Demo

    The test functionality and Query testing  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@hyper-space.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from hyperspace.api.hyperspace_api import HyperspaceApi
# import ApiClient
from hyperspace.api_client import ApiClient
from hyperspace.configuration import Configuration
# import models into sdk package
from hyperspace.models.auth_dto import AuthDto
from hyperspace.models.collection_name_dsl_search_body import CollectionNameDslSearchBody
from hyperspace.models.collection_name_search_body import CollectionNameSearchBody
from hyperspace.models.document import Document
from hyperspace.models.file_dto import FileDto
from hyperspace.models.inline_response200 import InlineResponse200
from hyperspace.models.login_dto import LoginDto
from hyperspace.models.status_dto import StatusDto
from hyperspace.hyperspace_client import HyperspaceClientApi
from hyperspace.ranking_logic_functions import *
